#coding: utf-8
'''
Triangular, pentagonal, and hexagonal
Problem 45
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''
import time

def Hexagonal(n):
	return n*(2*n-1)

def CheckIfPentagon(x):
	n = ((24*x + 1)**0.5 + 1)/6
	if n == int(n):
		return True
	return False
	
def CheckIfTriangle(x):
	n = (2*x + 0.25)**0.5 - 0.5
	if n == int(n):
		return True 
	return False
	
def doProblem():
	n = 143
	while True:
		n += 1
		hn = Hexagonal(n)
		if CheckIfPentagon(hn):
			if CheckIfTriangle(hn):
				return hn

print('start')
start = time.time()
print(doProblem())
print('end')
print(time.time()-start)
